### ISSUE TITLE
Corriger le layout mobile sur la liste des factures

### ISSUE THREAD

**Issue by tuxayo** [agilidee/backbone#157]
L'ajout de la colonne payé avec #122 passe sur écran large, mais pas sur mobile
![screen shot 2014-07-04 at 19 26 47](https://cloud.githubusercontent.com/assets/2678215/3602655/a96be496-0d0e-11e4-9c2d-71a412ef9cfe.png)

**Comment by bgantaume** [comment]
Revoir l'écran en 1024
