### ISSUE TITLE
Intégration de customer vault dans dorsale

### ISSUE THREAD

**Issue by bgantaume** [agilidee/backbone#221]

**Comment by BenoitMC** [comment]
La première partie de l'intégration de CV est fait sur la branche cv.
On peut gérer les contacts et les contacts sont isolés et protégé par entité.

Il faut maintenant basculer les factures sur CV.

Une migration a déjà été créée pour copier les customers dans CV.
Il faut maintenant les remplacer au niveau des factures pour supprimer complètement les customers.

**Comment by BenoitMC** [comment]
Dans les customers il y avait un champ "short_name", il a été créé dans les individuals et dans les corporations pour migrer les customers.

- [ ] Il faudra modifier les formulaires de CV pour pouvoir l'éditer.

**Comment by BenoitMC** [comment]
A supprimer concernant les customers : 

- [x] les features
- [ ] la factory
- [ ] la config activeadmin
- [ ] le contrôleur API

Plus tard : 

- [ ] le modèle

**Comment by BenoitMC** [comment]
Il faut adapter le filtre des factures par client

**Comment by BenoitMC** [comment]
- [ ] Vérifier dans le code qu'aucune recherche de facture n'est faire simplement par son `customer_id` mais bien par le couple `[customer_id, customer_type]` (par exemple les filtres).

**Comment by BenoitMC** [comment]
Après la migration : 

- [ ] Supprimer l'ancienne table `customers`
- [ ] Supprimer le champ `old_customer_id` de la table `invoices`
- [ ] Supprimer la modèle `Customer`

**Comment by BenoitMC** [comment]
- [ ] CustomerVault dépend de la branch dev de github, il faut le builder, le mettre sur rubygems, et modifier la dépendance dans Backbone.

**Comment by BenoitMC** [comment]
CV est intégré et fonctionne, on peut créer des personnes, les accès sont protégés par entité.

Le remplacement dans BillingMachine des customers fonctionne : 

- Le champ `customer_id` a été renommé en `old_customer_id` pour en conserver une trace pour le moment de l'ancien customer
- Des champs `customer_id` et `customer_type` ont été ajoutés aux invoices pour les câbler à CV
- Les customers ont été copiés dans CV en tant que corporations
- Les invoices ont été mises à jour avec les corporations nouvellement créées

J'ai nettoyé tout ce qui se rapporte aux anciens customers à part le modèle : il va servir à migrer les données.

J'ai poussé le test jusqu'au bout en supprimant temporairement même le modèle et tout les tests passent.

Il reste encore quelques modifications (voir ci-dessus) mais le gros est fait.

Avant de migrer la prod, il faudra faire essayer une migration en local avec les données de prod pour vérifier que tout est OK. La mise à jour est quand même importante.

**Comment by BenoitMC** [comment]
- [ ] Faire un point sur les destroy en cascade avec CV
