### ISSUE TITLE
Supprimer la ville des champs obligatoires

### ISSUE THREAD

**Issue by bgantaume** [agilidee/backbone#257]

**Comment by BenoitMC** [comment]
Directement dans Dorsale ou sur Backbone ?

Si on supprime la ville obligatoire, ça veut dire qu'aucun champ n'est obligatoire est qu'on peut donc créer des adresses vides...

**Comment by BenoitMC** [comment]
Par contre il faudrait peut-être valider la présence de l'adressable, ce qui n'est pas fait actuellement.

**Comment by bgantaume** [comment]
Bonne idee
Le 16 avr. 2015 2:10 PM, "Benoit MARTIN-CHAVE" <notifications@github.com> a
écrit :

**Comment by BenoitMC** [comment]
La validation de l'addressable fait tout placarder.

Rails va sauvegarder d'abord l'adresse et ensuite la personne, donc la validation ne passe pas parce que la personne n'existe pas encore.

Il faut que j'essaie d'inverser l'ordre d'enregistrement.

**Comment by BenoitMC** [comment]
Il fallait mettre et `inverse_of` sur **les deux modèles** et passer la factory de l'adresse en after_create.
