### ISSUE TITLE
cv : crash au filtre par zip code

### ISSUE THREAD

**Issue by bgantaume** [agilidee/backbone#259]
An ArgumentError occurred in people#index:

  comparison of CustomerVault::Corporation with CustomerVault::Corporation failed
  app/controllers/customer_vault/people_controller.rb:23:in `sort'

-------------------------------
Request:
-------------------------------

  * URL        : https://dorsale.cc/customer_vault/people?page=1&sort=zip
  * HTTP Method: GET
  * IP address : 80.215.228.68
  * Parameters : {"page"=>"1", "sort"=>"zip", "action"=>"index", "controller"=>"customer_vault/people"}
  * Timestamp  : 2015-03-27 14:30:11 UTC
  * Server : kaukura19.ouvrages
  * Rails root : /home/backbone-production/backbone
  * Process: 6039

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: #<ActionDispatch::Request::Session:0x957bc24 ...>

-------------------------------
Environment:
-------------------------------

  * DOCUMENT_ROOT                                  : /home/backbone-production/backbone/public
  * HTTPS                                          : on
  * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, sdch
  * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.8,fr;q=0.6
  * HTTP_CONNECTION                                : keep-alive
  * HTTP_COOKIE                                    : _backbone_session=VmwvZ0J5NGhEbUFzVlZNV2NEMFpCTm5VSitTYzl1WDlwM0JwYytDZkN6R1N0NE4wbEFkd3MrOHg0YTZaYW1JUUhHalZtaE80V21RQ202T0YrQzZxaUlNRWhCbTd4L3FFSGtEeG5DMzByc1U4bjY3MnpDU21QdDlzOFdkSzJoNjc0bVNXWUQzdklSdU5qcEVwS0QvTmVDUEtyRHZwc2kwb2xLaHRGRkdHRU92VzhCMGRQUjlZNHRxdUhlemlGMU1jRkd2WEVFaE9IQUlVSzlOdWpCcGV3aEtIQlNNeG1jeXd0Rnhxdmt6a0Z1Q0pNL21RbGM2U0NJRFYyQ2JoTGJPQ2RpSDBwTWZDQmpwZ3htM0dHTjlhenc9PS0tN010OGN1TGlibHNrOXllSnkybWpJZz09--6b5476a0f9cbe176fd1478990e995b67f32660cc
  * HTTP_HOST                                      : dorsale.cc
  * HTTP_REFERER                                   : https://dorsale.cc/customer_vault/people
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36
  * ORIGINAL_FULLPATH                              : /customer_vault/people?page=1&sort=zip
  * ORIGINAL_SCRIPT_NAME                           :
  * PASSENGER_APP_ENV                              : production
  * PASSENGER_APP_TYPE                             : rack
  * PASSENGER_CONNECT_PASSWORD                     : [FILTERED]
  * PASSENGER_FRIENDLY_ERROR_PAGES                 : false
  * PASSENGER_MIN_PROCESSES                        : 1
  * PATH_INFO                                      : /people
  * QUERY_STRING                                   : page=1&sort=zip
  * REMOTE_ADDR                                    : 80.215.228.68
  * REMOTE_PORT                                    : 12537
  * REQUEST_METHOD                                 : GET
  * REQUEST_URI                                    : /customer_vault/people?page=1&sort=zip
  * ROUTES_73674100_SCRIPT_NAME                    : /customer_vault
  * ROUTES_87058440_SCRIPT_NAME                    :
  * SCGI                                           : 1
  * SCRIPT_NAME                                    : /customer_vault
  * SERVER_ADDR                                    : 212.129.26.248
  * SERVER_NAME                                    : dorsale.cc
  * SERVER_PORT                                    : 443
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : nginx/1.6.1
  * action_controller.instance                     : #<CustomerVault::PeopleController:0x8a4c1a0>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0xa7cc658>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0xa675ebc>
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0xa7ca484>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0xa33fb44>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 80.215.228.68
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [text/html]
  * action_dispatch.request.parameters             : {"page"=>"1", "sort"=>"zip", "action"=>"index", "controller"=>"customer_vault/people"}
  * action_dispatch.request.path_parameters        : {:action=>"index", :controller=>"customer_vault/people"}
  * action_dispatch.request.query_parameters       : {"page"=>"1", "sort"=>"zip"}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"a0c0a9ef25c4334a198e9db4c55c44a3", "warden.user.user.key"=>[[1], "$2a$10$ERJO9k9k7eStejQ1svWE4e"], "_csrf_token"=>"6h/1I8dYZJGOnEQwZRrJiM/lIZQpJMoYDLv2S7hweRE="}
  * action_dispatch.request_id                     : abfd8d9e-1fb6-40b4-b130-97b9bb515bf3
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x8c85ae8>
  * action_dispatch.secret_key_base                : 20e159ba72e42c6342aa68fe331be8c94fbd5ff9d5f0c95df03aae862b610b3dfbbe0b2f90519b47331599e576982609cd96ca9f3916eed89e93ae781f46f0ae
  * action_dispatch.secret_token                   :
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * rack.errors                                    : #<IO:0x84c28d8>
  * rack.hijack                                    : #<Proc:0x9151874@/var/lib/gems/1.9.1/gems/passenger-4.0.50/lib/phusion_passenger/rack/thread_handler_extension.rb:69 (lambda)>
  * rack.hijack?                                   : true
  * rack.input                                     : #<PhusionPassenger::Utils::TeeInput:0xaaaa744>
  * rack.multiprocess                              : true
  * rack.multithread                               : false
  * rack.request.cookie_hash                       : {"_backbone_session"=>"VmwvZ0J5NGhEbUFzVlZNV2NEMFpCTm5VSitTYzl1WDlwM0JwYytDZkN6R1N0NE4wbEFkd3MrOHg0YTZaYW1JUUhHalZtaE80V21RQ202T0YrQzZxaUlNRWhCbTd4L3FFSGtEeG5DMzByc1U4bjY3MnpDU21QdDlzOFdkSzJoNjc0bVNXWUQzdklSdU5qcEVwS0QvTmVDUEtyRHZwc2kwb2xLaHRGRkdHRU92VzhCMGRQUjlZNHRxdUhlemlGMU1jRkd2WEVFaE9IQUlVSzlOdWpCcGV3aEtIQlNNeG1jeXd0Rnhxdmt6a0Z1Q0pNL21RbGM2U0NJRFYyQ2JoTGJPQ2RpSDBwTWZDQmpwZ3htM0dHTjlhenc9PS0tN010OGN1TGlibHNrOXllSnkybWpJZz09--6b5476a0f9cbe176fd1478990e995b67f32660cc"}
  * rack.request.cookie_string                     : _backbone_session=VmwvZ0J5NGhEbUFzVlZNV2NEMFpCTm5VSitTYzl1WDlwM0JwYytDZkN6R1N0NE4wbEFkd3MrOHg0YTZaYW1JUUhHalZtaE80V21RQ202T0YrQzZxaUlNRWhCbTd4L3FFSGtEeG5DMzByc1U4bjY3MnpDU21QdDlzOFdkSzJoNjc0bVNXWUQzdklSdU5qcEVwS0QvTmVDUEtyRHZwc2kwb2xLaHRGRkdHRU92VzhCMGRQUjlZNHRxdUhlemlGMU1jRkd2WEVFaE9IQUlVSzlOdWpCcGV3aEtIQlNNeG1jeXd0Rnhxdmt6a0Z1Q0pNL21RbGM2U0NJRFYyQ2JoTGJPQ2RpSDBwTWZDQmpwZ3htM0dHTjlhenc9PS0tN010OGN1TGlibHNrOXllSnkybWpJZz09--6b5476a0f9cbe176fd1478990e995b67f32660cc
  * rack.request.query_hash                        : {"page"=>"1", "sort"=>"zip"}
  * rack.request.query_string                      : page=1&sort=zip
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x957bc24>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x8e30fc8>
  * rack.url_scheme                                : https
  * rack.version                                   : [1, 2]
  * warden                                         : Warden::Proxy:72670650 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:rememberable, :token_authenticatable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0xa4c31f0>}

-------------------------------
Backtrace:
-------------------------------

  app/controllers/customer_vault/people_controller.rb:23:in `sort'
  app/controllers/customer_vault/people_controller.rb:23:in `block in index'
  app/controllers/customer_vault/people_controller.rb:17:in `index'

**Comment by BenoitMC** [comment]
J'arrive pas à reproduire en local. Je ferai un import de la base de prod debut de semaine prochaine pour essayer de trouver d'où ça vient.

**Comment by BenoitMC** [comment]
J'ai changé la méthode de tri dans CV.
Vérifier si le problème est encore là après la mise en prod.

**Comment by BenoitMC** [comment]
Le problème vient du fait que certains codes postaux sont à nil et ne peuvent être comparés avec des strings.

Lors de la migration des customers de billing_machine, certains codes postaux se sont retrouvé à `nil`, ce qui n'arrivait jamais avant puisqu'en créant les personnes depuis le formulaire, les champs se mettent en empty string et non en nil.
