### ISSUE TITLE
affichage illisible

### ISSUE THREAD

**Issue by bgantaume** [agilidee/backbone#260]
ranger les informations de sorte à ce que cela reste lisible et éviter que les textes soient tronqués

![people_list](https://cloud.githubusercontent.com/assets/1662023/6869745/b1b35800-d496-11e4-93e9-6e277f0d8969.png)

**Comment by bgantaume** [comment]
Pendant que l'on travaille sur ce morceau, mettre les actions en bouton (btn-xs) et alignés à droite

**Comment by BenoitMC** [comment]
@bgantaume J'étais justement en train de faire un peu de propre dans tout ça : arranger les vues, merger les show des individuals et des corporations qui sont identiques, ...
