### ISSUE TITLE
:show person

### ISSUE THREAD

**Issue by bgantaume** [agilidee/backbone#277]
Comme pour une tâche, mettre la description en bas et l'historique le plus récent en haut. 
Le formulaire d'ajout est tout en haut.

**Comment by BenoitMC** [comment]
J'ai inversé l'ordre et mis le formulaire en haut.
Par contre c'est quoi que tu appelles la description sur une personne ?

cc @bgantaume

**Comment by bgantaume** [comment]
Le detail de la fiche.
En bas de la colonne de contexte.
Le 16 avr. 2015 2:18 PM, "Benoit MARTIN-CHAVE" <notifications@github.com> a
écrit :
