### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by bgantaume** [agilidee/backbone#298]
A NoMethodError occurred in individuals#create:

  undefined method `id' for nil:NilClass
  app/models/customer_vault/person.rb:16:in `block in tag_list='

-------------------------------
Request:
-------------------------------

  * URL        : https://dorsale.cc/customer_vault/individuals
  * HTTP Method: POST
  * IP address : 195.132.223.40
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"D9ed0+2f+6g95M29zta9sIRFhgWCjoAnf63u+rIsnT4=", "individual"=>{"first_name"=>"Raymond", "last_name"=>"Haas", "tag_list"=>["", "Zoé"], "email"=>"", "title"=>"", "twitter"=>"", "context"=>"", "phone"=>"", "fax"=>"", "mobile"=>"", "www"=>"", "address_attributes"=>{"street"=>"", "street_bis"=>"", "zip"=>"", "city"=>"Marseille", "country"=>""}}, "action"=>"create", "controller"=>"customer_vault/individuals"}
  * Timestamp  : 2015-04-22 09:04:07 UTC
  * Server : kaukura19.ouvrages
  * Rails root : /home/backbone-production/backbone
  * Process: 12431

-------------------------------
Session:
-------------------------------

  * session id: [FILTERED]
  * data: #<ActionDispatch::Request::Session:0xc9bf3c8 ...>

-------------------------------
Environment:
-------------------------------

  * CONTENT_LENGTH                                 : 658
  * CONTENT_TYPE                                   : application/x-www-form-urlencoded
  * DOCUMENT_ROOT                                  : /home/backbone-production/backbone/public
  * HTTPS                                          : on
  * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate
  * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.8,fr;q=0.6
  * HTTP_CACHE_CONTROL                             : max-age=0
  * HTTP_CONNECTION                                : keep-alive
  * HTTP_COOKIE                                    : remember_user_token=BAhbB1sGaQZJIiIkMmEkMTAkRVJKTzlrOWs3ZVN0ZWpRMX

**Comment by BenoitMC** [comment]
Le problème venait du fait que dans Backbone on préfixe les tags avec l'id de l'entity.
Le tags étaient affectés avant l'entité, elle n'était donc pas dispo pour créer les tags.
